# Generated by Django 6.0.3 on 2026-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.CharField(max_length=10, unique=True)),
                ('college_name', models.CharField(max_length=255)),
            ],
        ),
    ]
