from rest_framework import serializers
from .models import Event, AttendanceLog, Bookmark, Feedback
from organizations.models import Organization
from bson import ObjectId
from .utils import filter_by_object_id


class ObjectIdField(serializers.Field):
    """Handles serialization/deserialization of MongoDB ObjectId fields."""

    def to_representation(self, value):
        # ObjectId → string for GET responses
        return str(value)

    def to_internal_value(self, data):
        # string → validate on POST/PUT
        if not ObjectId.is_valid(str(data)):
            raise serializers.ValidationError("Invalid ObjectId format.")
        return str(data)  # keep as string; model CharField stores it as string


class EventSerializer(serializers.ModelSerializer):
    _id = ObjectIdField(required=False)  # auto-generated by MongoDB, not required on POST
    event_image_file = serializers.ImageField(write_only=True, required=False)
    organization_id = serializers.CharField(max_length=24)

    class Meta:
        model = Event
        fields = '__all__'

    def validate_organization_id(self, value):
        if not ObjectId.is_valid(value):
            raise serializers.ValidationError("Invalid MongoDB ObjectId.")

        # Use ObjectId when querying so djongo doesn't try to cast it as int
        if not filter_by_object_id(Organization.objects, '_id', value).exists():
            raise serializers.ValidationError("Organization not found.")

        return value  # return as string; stored in CharField

    def create(self, validated_data):
        image_file = validated_data.pop('event_image_file', None)
        if image_file:
            import cloudinary.uploader
            result = cloudinary.uploader.upload(image_file)
            validated_data['event_image'] = result['secure_url']
        return super().create(validated_data)

    def update(self, instance, validated_data):
        image_file = validated_data.pop('event_image_file', None)
        if image_file:
            import cloudinary.uploader
            result = cloudinary.uploader.upload(image_file)
            validated_data['event_image'] = result['secure_url']
        return super().update(instance, validated_data)


class AttendanceLogSerializer(serializers.ModelSerializer):
    _id = ObjectIdField(required=False)

    class Meta:
        model = AttendanceLog
        fields = '__all__'


class BookmarkSerializer(serializers.ModelSerializer):
    _id = ObjectIdField(required=False)

    class Meta:
        model = Bookmark
        fields = '__all__'


class FeedbackSerializer(serializers.ModelSerializer):
    _id = ObjectIdField(required=False)

    class Meta:
        model = Feedback
        fields = '__all__'